
public class Even_Fibonacci_Numbers {
	public static void main(String[] args) {
		int a = 1, b = 2, max = 2000000, even_sum = 0;
		while ( a < max | b < max) {
			a += b;
			if (a % 2 == 0) {
				even_sum += a;
			}
			b += a;
			if (b % 2 == 0) {
				even_sum += b;
			}	
		}
		System.out.println((even_sum + 2));	
	}
}
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.






